import { test, expect, type Page } from '@playwright/test'
import AxeBuilder from '@axe-core/playwright'

async function login(page: Page) {
  await page.goto('/admin/login')
  await page.getByLabel('Email', { exact: true }).fill('editor@example.test')
  await page.getByLabel('Password', { exact: true }).fill('Browser-fixture-password-2026!')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Posts', exact: true })).toBeVisible()
}

test('real publishing workflow: login, bilingual Markdown, publish, comment, moderation', async ({ page, browser }) => {
  const errors: string[] = []
  page.on('pageerror', (error) => errors.push(error.message))
  await login(page)
  await page.getByRole('link', { name: 'New post', exact: true }).click()
  await page.getByLabel('Title (English)', { exact: true }).fill('A real publishing walkthrough')
  await page.getByLabel('Excerpt (English)', { exact: true }).fill('From the editor to a readable public article.')
  await page.locator('#body-en').fill('## A real workflow\n\nThis article was written through the **OSBlog editor**.\n\n- Markdown preview\n- A custom slug\n- Moderated comments')
  await page.getByRole('button', { name: 'Split mode', exact: true }).first().click()
  await expect(page.locator('.editor-preview strong')).toHaveText('OSBlog editor')
  await page.getByRole('tab', { name: 'Tiếng Việt', exact: true }).click()
  await page.getByLabel('Tiêu đề (Tiếng Việt)', { exact: true }).fill('Một quy trình xuất bản thực tế')
  await page.getByLabel('Tóm tắt (Tiếng Việt)', { exact: true }).fill('Từ editor đến bài viết công khai dễ đọc.')
  await page.locator('#body-vi').fill('## Quy trình thực tế\n\nBài viết được tạo bằng **editor của OSBlog**.')
  await page.getByLabel('Slug', { exact: true }).fill('real-publishing-walkthrough')
  await page.getByRole('combobox', { name: 'Category', exact: true }).selectOption({ label: 'Open source' })
  await page.getByRole('tab', { name: 'English', exact: true }).click()
  await page.screenshot({ path: 'test-results/editor-desktop.png', fullPage: true })
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  // Publishing a new post intentionally redirects to its edit route, so the
  // transient save status is replaced by the loaded persisted record. Verify
  // the public result below instead of asserting an unmounted toast.
  await expect(page).toHaveURL(/\/admin\/posts\/[^/]+\/edit$/)
  await expect(page.getByRole('heading', { name: 'A real publishing walkthrough', exact: true })).toBeVisible()
  const visitor = await browser.newPage({ viewport: { width: 1440, height: 1000 } })
  await visitor.goto('/post/real-publishing-walkthrough?lang=en')
  await expect(visitor.getByRole('heading', { name: 'A real publishing walkthrough', exact: true })).toBeVisible()
  await expect(visitor.locator('.md-body strong')).toHaveText('OSBlog editor')
  await page.getByLabel('Slug', { exact: true }).fill('renamed-publishing-walkthrough')
  await expect(page.getByText(/Previously published URLs permanently redirect/)).toBeVisible()
  await page.getByRole('button', { name: 'Publish', exact: true }).click()
  await expect(page.getByText('Post published.', { exact: true })).toBeVisible()
  await expect(page.getByText(/Previously published URLs permanently redirect/)).toHaveCount(0)
  for (const lang of ['vi', 'en']) {
    const landed = await visitor.goto(`/post/real-publishing-walkthrough?lang=${lang}&ignored=true`)
    expect(landed?.status()).toBe(200)
    expect(landed?.request().redirectedFrom()?.url()).toContain('/post/real-publishing-walkthrough?')
    await expect(visitor).toHaveURL(new RegExp(`/post/renamed-publishing-walkthrough\\?lang=${lang}$`))
    await expect(visitor.getByRole('heading', { name: lang === 'vi' ? 'Một quy trình xuất bản thực tế' : 'A real publishing walkthrough', exact: true })).toBeVisible()
  }
  const sitemap = await (await visitor.request.get('/sitemap.xml')).text()
  expect(sitemap).toContain('/post/renamed-publishing-walkthrough?lang=en')
  expect(sitemap).not.toContain('/post/real-publishing-walkthrough?')
  await visitor.getByLabel('Email', { exact: true }).fill('reader@example.test')
  await visitor.getByLabel('Your note', { exact: true }).fill('The publishing flow works from start to finish.')
  await visitor.getByRole('button', { name: 'Send for review' }).click()
  await expect(visitor.getByRole('status')).toContainText('pending moderation')
  await visitor.reload()
  await expect(visitor.locator('.comment-list')).toHaveCount(0)
  await page.goto('/admin/comments')
  await expect(page.getByText('The publishing flow works from start to finish.', { exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Approve', exact: true }).click()
  await visitor.reload()
  await expect(visitor.locator('.comment-list')).toContainText('The publishing flow works from start to finish.')
  await expect(visitor.locator('.comment-list')).not.toContainText('reader@example.test')
  await visitor.screenshot({ path: 'test-results/article-desktop.png', fullPage: true })
  expect(errors).toEqual([])
  await visitor.close()
})

test('public SSR, mobile docs, keyboard and automated accessibility', async ({ page, request }) => {
  const response = await request.get('/post/welcome-to-osblog?lang=vi')
  expect(response.status()).toBe(200)
  const source = await response.text()
  expect(source).toContain('Một mái nhà nhỏ cho những ý tưởng mở')
  expect(source).toMatch(/\/assets\/index-[\w-]+\.js/)
  expect(source).not.toContain('/src/main.tsx')
  await page.goto('/?lang=en')
  const home = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(home.violations).toEqual([])
  await page.screenshot({ path: 'test-results/home-desktop.png', fullPage: true })
  await page.setViewportSize({ width: 390, height: 844 })
  await page.goto('/docs/editor?lang=vi')
  await expect(page.locator('html')).toHaveAttribute('lang', 'vi')
  const docs = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze()
  expect(docs.violations).toEqual([])
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBe(true)
  await page.screenshot({ path: 'test-results/docs-mobile.png', fullPage: true })
})
