// Generated by the common Vite SSR build before Netlify bundles the function.
import { handle } from '../../dist/server/index.js'
export default (request: Request, context: { ip: string }) => handle(request, { ip: context.ip })
